"""empty message

Revision ID: 3e125baccac3
Revises: 6f0fab4481ea
Create Date: 2017-04-09 22:22:33.764000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e125baccac3'
down_revision = '6f0fab4481ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'avatar')
    # ### end Alembic commands ###
