"""empty message

Revision ID: b9881f4f5f3d
Revises: b5de238dfec2
Create Date: 2017-04-08 17:31:07.530000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9881f4f5f3d'
down_revision = 'b5de238dfec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('old_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'old_login_time')
    # ### end Alembic commands ###
