"""empty message

Revision ID: bb64befb1c4c
Revises: 6cc89fd204a7
Create Date: 2017-04-15 15:00:57.544000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb64befb1c4c'
down_revision = '6cc89fd204a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('is_sign_in', sa.Boolean(), nullable=True))
    op.drop_column('signin', 'is_sign_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signin', sa.Column('is_sign_in', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('front_user', 'is_sign_in')
    # ### end Alembic commands ###
